build:
  version: "3.0"

accounts:
  message: "Welcome to Eazy Bank Accounts related local APIs"
  contactDetails:
    email: "email@example.com"
    name: "Eazy Bank"
  onCallSupport:
    - (555) 555-1234
    - (555) 555-1235